### ISSUE TITLE
Installation fails on Windows with python 3.9

### ISSUE THREAD

**Issue by Alexander-Serov** [louisabraham/pydivsufsort#29]
Hi!

I have been using `pydivsufsort` happily, until we decided to move on to python 3.9. Now here is what I get when attempting to install it:
```
> pip install pydivsufsort
Looking in indexes: https://pypi.org/simple, https://__token__:****@gitlab.edf-sf.com/api/v4/projects/319/packages/pypi/simple
Collecting pydivsufsort
  Using cached pydivsufsort-0.0.5.tar.gz (222 kB)
Requirement already satisfied: wheel in c:\tools\miniconda3\envs\anomaly-39\lib\site-packages (from pydivsufsort) (0.37.0)
Requirement already satisfied: numpy in c:\tools\miniconda3\envs\anomaly-39\lib\site-packages (from pydivsufsort) (1.21.2)
Building wheels for collected packages: pydivsufsort
  Building wheel for pydivsufsort (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\tools\miniconda3\envs\anomaly-39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-d8dkl01o\\pydivsufsort_798d6c3db82d498a9623f5bbe36b9556\\setup.py'"'"'; __file__='"'
"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-d8dkl01o\\pydivsufsort_798d6c3db82d498a9623f5bbe36b9556\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup(
)'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\user\AppData\Local\Temp\pip-wheel-taw7f0qg'
       cwd: C:\Users\user\AppData\Local\Temp\pip-install-d8dkl01o\pydivsufsort_798d6c3db82d498a9623f5bbe36b9556\
  Complete output (23 lines):
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\user\AppData\Local\Temp\pip-install-d8dkl01o\pydivsufsort_798d6c3db82d498a9623f5bbe36b9556\setup.py", line 60, in <module>
      setup(
    File "C:\tools\miniconda3\envs\anomaly-39\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\tools\miniconda3\envs\anomaly-39\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\tools\miniconda3\envs\anomaly-39\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\tools\miniconda3\envs\anomaly-39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\tools\miniconda3\envs\anomaly-39\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\tools\miniconda3\envs\anomaly-39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\tools\miniconda3\envs\anomaly-39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\user\AppData\Local\Temp\pip-install-d8dkl01o\pydivsufsort_798d6c3db82d498a9623f5bbe36b9556\setup.py", line 33, in run
      assert witness.exists(), "Launch ./build.sh first"
  AssertionError: Launch ./build.sh first
  ----------------------------------------
  ERROR: Failed building wheel for pydivsufsort
  Running setup.py clean for pydivsufsort
Failed to build pydivsufsort
Installing collected packages: pydivsufsort
    Running setup.py install for pydivsufsort ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\tools\miniconda3\envs\anomaly-39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-d8dkl01o\\pydivsufsort_798d6c3db82d498a9623f5bbe36b9556\\setup.py'"'"'; __file__='
"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-d8dkl01o\\pydivsufsort_798d6c3db82d498a9623f5bbe36b9556\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setu
p()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-pqje_tnd\install-record.txt' --single-version-externally-managed --compile --inst
all-headers 'C:\tools\miniconda3\envs\anomaly-39\Include\pydivsufsort'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-d8dkl01o\pydivsufsort_798d6c3db82d498a9623f5bbe36b9556\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\tools\miniconda3\envs\anomaly-39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-d8dkl01o\\pydivsufsort_798d6c3db82d498a9623f5bbe3
6b9556\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-d8dkl01o\\pydivsufsort_798d6c3db82d498a9623f5bbe36b9556\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'f
rom setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-pqje_tnd\install-record.txt' --single-version-ex
ternally-managed --compile --install-headers 'C:\tools\miniconda3\envs\anomaly-39\Include\pydivsufsort' Check the logs for full command output.
```

Do you have any idea what is going wrong and how to fix it perhaps?

Thanks!

**Comment by louisabraham** [comment]
Can you test again? I relaunched the Travis CI to upload prebuilt wheels of the windows package.
Building from source on windows can still not be done with just one command.

**Comment by Alexander-Serov** [comment]
Thanks for the fast reply. The installation seems to go through correctly now!

I guess we can close.
