### ISSUE TITLE
v0.0.11 contains x86 instead of arm64 on Mac M1

### ISSUE THREAD

**Issue by GeorgWa** [louisabraham/pydivsufsort#46]
## Issue 
(See #45)
Unfortunately there still seems to be an issue when installing in a clean conda environment on Mac M1:

v0.0.10 runs through just fine
`pip install pydivsufsort==0.0.10 && python -c 'from pydivsufsort import divsufsort'`

v0.0.11 fails:
`pip install pydivsufsort==0.0.11 && python -c 'from pydivsufsort import divsufsort'`

```
Using cached pydivsufsort-0.0.11-cp311-cp311-macosx_11_0_arm64.whl (284 kB)
Installing collected packages: pydivsufsort
  Attempting uninstall: pydivsufsort
    Found existing installation: pydivsufsort 0.0.10
    Uninstalling pydivsufsort-0.0.10:
      Successfully uninstalled pydivsufsort-0.0.10
Successfully installed pydivsufsort-0.0.11
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/__init__.py", line 1, in <module>
    from .divsufsort import divsufsort, bw_transform, inverse_bw_transform, sa_search
  File "/Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/divsufsort.py", line 11, in <module>
    from .dll import libdivsufsort, libdivsufsort64
  File "/Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/dll.py", line 18, in <module>
    libdivsufsort = ctypes.CDLL(PATH_LIBDIVSUFSORT)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/libdivsufsort.3.0.1.dylib, 0x0006): tried: '/Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/libdivsufsort.3.0.1.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```
## conda info 

```
conda info

     active environment : testpydivsufsort
    active env location : /Users/georgwallmann/miniconda3/envs/testpydivsufsort
            shell level : 7
       user config file : /Users/georgwallmann/.condarc
 populated config files : 
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __osx=12.5.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/georgwallmann/miniconda3  (writable)
      conda av data dir : /Users/georgwallmann/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/georgwallmann/miniconda3/pkgs
                          /Users/georgwallmann/.conda/pkgs
       envs directories : /Users/georgwallmann/miniconda3/envs
                          /Users/georgwallmann/.conda/envs
               platform : osx-arm64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.12 Darwin/21.6.0 OSX/12.5.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

## conda list

```
# packages in environment at /Users/georgwallmann/miniconda3/envs/testpydivsufsort:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h620ffc9_4  
ca-certificates           2023.08.22           hca03da5_0  
libffi                    3.4.4                hca03da5_0  
ncurses                   6.4                  h313beb8_0  
numpy                     1.26.1                   pypi_0    pypi
openssl                   3.0.12               h1a28f6b_0  
pip                       23.3            py311hca03da5_0  
pydivsufsort              0.0.11                   pypi_0    pypi
python                    3.11.5               hb885b13_0  
readline                  8.2                  h1a28f6b_0  
setuptools                68.0.0          py311hca03da5_0  
sqlite                    3.41.2               h80987f9_0  
tk                        8.6.12               hb8d0fd4_0  
tzdata                    2023c                h04d1e81_0  
wheel                     0.41.2          py311hca03da5_0  
xz                        5.4.2                h80987f9_0  
zlib                      1.2.13               h5a0b063_0 
```

**Comment by louisabraham** [comment]
Could you run:

```
python -c 'import platform; print(platform.machine())'
```

?

**Comment by GeorgWa** [comment]
Hi, thank you for the fast response!

```
(testpydivsufsort) georgwallmann@Georgs-MBP ~ % conda activate testpydivsufsort                       
(testpydivsufsort) georgwallmann@Georgs-MBP ~ % python -c 'import platform; print(platform.machine())'
arm64
```

**Comment by louisabraham** [comment]
What does `pip install pydivsufsort==0.0.10` output? Does it compile the library itself?

**Comment by GeorgWa** [comment]
## v0.0.11
```
(testpydivsufsort) georgwallmann@Georgs-MBP pydivsufsort % pip install pydivsufsort==0.0.11                                                                                                       
Collecting pydivsufsort==0.0.11
  Using cached pydivsufsort-0.0.11-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.9 kB)
Requirement already satisfied: wheel in /Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages (from pydivsufsort==0.0.11) (0.41.2)
Requirement already satisfied: numpy in /Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages (from pydivsufsort==0.0.11) (1.26.1)
Using cached pydivsufsort-0.0.11-cp311-cp311-macosx_11_0_arm64.whl (284 kB)
Installing collected packages: pydivsufsort
  Attempting uninstall: pydivsufsort
    Found existing installation: pydivsufsort 0.0.10
    Uninstalling pydivsufsort-0.0.10:
      Successfully uninstalled pydivsufsort-0.0.10
Successfully installed pydivsufsort-0.0.11
```
### Checksums
```
(testpydivsufsort) georgwallmann@Georgs-MBP pydivsufsort % shasum -a 256 /Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/libdivsufsort.3.0.1.dylib  
4564e59e3557806f2c8492c3be0f1bb195ab0b19695e4a282c52c8a01f642864  /Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/libdivsufsort.3.0.1.dylib
(testpydivsufsort) georgwallmann@Georgs-MBP pydivsufsort % shasum -a 256 /Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/libdivsufsort64.3.0.1.dylib
1a072dbc2d117fc9dfd5eff17f72a82f34c9ccb32a6290b34b43091414d0a605  /Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/libdivsufsort64.3.0.1.dylib
```

## v.0.0.10

```
(testpydivsufsort) georgwallmann@Georgs-MBP ~ % pip install pydivsufsort==0.0.10
Collecting pydivsufsort==0.0.10
  Using cached pydivsufsort-0.0.10-cp311-cp311-macosx_12_0_arm64.whl
Requirement already satisfied: wheel in ./miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages (from pydivsufsort==0.0.10) (0.41.2)
Requirement already satisfied: numpy in ./miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages (from pydivsufsort==0.0.10) (1.26.1)
Installing collected packages: pydivsufsort
  Attempting uninstall: pydivsufsort
    Found existing installation: pydivsufsort 0.0.11
    Uninstalling pydivsufsort-0.0.11:
      Successfully uninstalled pydivsufsort-0.0.11
Successfully installed pydivsufsort-0.0.10
```

### Checksums
```
(testpydivsufsort) georgwallmann@Georgs-MBP ~ % shasum -a 256 /Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/libdivsufsort.3.0.1.dylib  
29d8e56654be05c6c178cd7b1e82b45e631dbbd3f04e6b98f170d180461bb8e8  /Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/libdivsufsort.3.0.1.dylib
(testpydivsufsort) georgwallmann@Georgs-MBP ~ % shasum -a 256 /Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/libdivsufsort64.3.0.1.dylib
989fa665409a1172a1386c150e37795f6981ce25e3782349a8e8fa7df86f5949  /Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/libdivsufsort64.3.0.1.dylib
```

**Comment by louisabraham** [comment]
Well, `pydivsufsort-0.0.10-cp311-cp311-macosx_12_0_arm64.whl` does not come from PyPI  so you built it yourself previously.

I think you could try `pip install --no-binary pydivsufsort pydivsufsort==0.0.11`.

I think the problem is that cross-compilation does not compile the dylib correctly.

**Comment by GeorgWa** [comment]
Interesting, I wasn't actually aware that wheels are cached across environments.

Installing it using `pip install --no-binary pydivsufsort pydivsufsort==0.0.11` works fine.
So this seemed to be constrained to my wheel.

What do you mean by cross-compilation? shouldn't it be arm64 on arm64?

**Comment by louisabraham** [comment]
The problem is that the build process is cross-compiling arm64 on x86 machines. I am testing another way, we will see if it works.

**Comment by louisabraham** [comment]
I manually deleted the faulty files from pypi, now installation (without pre-compiled wheels) should work for version 0.0.11.

**Comment by GeorgWa** [comment]
Ah I see.. I realized we didn't have M1 acrtions runner so far, so I also implemented this on our site to catch similar issues next time.

Your help was greatly appreciated!

**Comment by louisabraham** [comment]
I'm trying to build wheels for arm64 [here](https://github.com/louisabraham/pydivsufsort/actions/runs/6751731794). Please test version 0.0.12.

**Comment by louisabraham** [comment]
@GeorgWa could you test it?

**Comment by GeorgWa** [comment]
Unfortunately it doesn't work. I cleared my wheels cache and used the same command as before:

```
(testpydivsufsort) georgwallmann@Georgs-MacBook-Pro ~ % pip install pydivsufsort==0.0.12 && python -c 'from pydivsufsort import divsufsort'


Collecting pydivsufsort==0.0.12
  Downloading pydivsufsort-0.0.12-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.9 kB)
Requirement already satisfied: wheel in ./miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages (from pydivsufsort==0.0.12) (0.41.2)
Requirement already satisfied: numpy in ./miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages (from pydivsufsort==0.0.12) (1.26.1)
Downloading pydivsufsort-0.0.12-cp311-cp311-macosx_11_0_arm64.whl (284 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.3/284.3 kB 4.0 MB/s eta 0:00:00
Installing collected packages: pydivsufsort
  Attempting uninstall: pydivsufsort
    Found existing installation: pydivsufsort 0.0.10
    Uninstalling pydivsufsort-0.0.10:
      Successfully uninstalled pydivsufsort-0.0.10
Successfully installed pydivsufsort-0.0.12
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/__init__.py", line 1, in <module>
    from .divsufsort import divsufsort, bw_transform, inverse_bw_transform, sa_search
  File "/Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/divsufsort.py", line 11, in <module>
    from .dll import libdivsufsort, libdivsufsort64
  File "/Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/dll.py", line 18, in <module>
    libdivsufsort = ctypes.CDLL(PATH_LIBDIVSUFSORT)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/libdivsufsort.3.0.1.dylib, 0x0006): tried: '/Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/libdivsufsort.3.0.1.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/libdivsufsort.3.0.1.dylib' (no such file), '/Users/georgwallmann/miniconda3/envs/testpydivsufsort/lib/python3.11/site-packages/pydivsufsort/libdivsufsort.3.0.1.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by louisabraham** [comment]
Could you test again with 0.0.14? I think I found the solution using `sysconfig.get_platform()` to detect when cibuildwheels is cross-compiling and `CMAKE_OSX_ARCHITECTURES` to cross-compile libdivsufsort.
